version: "3.7"
services:
  web:
    build: .
    container_name: choco_web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    links:
      - db
      - redis
    volumes:
      - .:/choco
      - api_gem_data:/usr/local/bundle
  db:
    image: mysql:8.0
    container_name: choco_db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-development-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=develop
  redis:
    container_name: choco_redis
    image: redis
    ports:
      - "6379:6379"
volumes:
  mysql-development-data:
  api_gem_data:
