name: Push To CodeCommit

on:
  push:
    branches:
      - main

jobs:
  push_to_codecommit:
    name: Push Source Code to CodeCommit
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch

      - name: Push to CodeCommit
        shell: bash
        env:
          CODECOMMIT_HOST: ${{ secrets.CODECOMMIT_HOST }}
          CODECOMMIT_REPO_URL: ${{ secrets.CODECOMMIT_REPO_URL }}
          CODECOMMIT_SSH_CONFIG: ${{ secrets.CODECOMMIT_SSH_CONFIG }}
          CODECOMMIT_SSH_PRIVATE_KEY: ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }}
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        run: |
          mkdir ~/.ssh
          echo "$CODECOMMIT_SSH_PRIVATE_KEY" > ~/.ssh/codecommit_rsa && chmod 600 ~/.ssh/codecommit_rsa
          echo "$CODECOMMIT_SSH_CONFIG" > ~/.ssh/config && chmod 600 ~/.ssh/config
          ssh-keyscan "$CODECOMMIT_HOST" >> ~/.ssh/known_hosts && chmod 600 ~/.ssh/known_hosts
          git remote add codecommit "$CODECOMMIT_REPO_URL"
          git push codecommit main:main
