name: Lint Check by Rubocop
on:
  push:
    branches:
      - develop
  pull_request:
    branchs:
      - develop

jobs:
  rspec:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/nysdin/choco_backend:develop
      env: RAILS_ENV=development

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup gem
        run: bundle install

      - name: bundle exec rubocop
        run: bundle exec rubocop
